implement signed integer encoding/decoding
mdlayher/netlink pull request #185
Opened 2021-02-20 19:20 UTC by fbegyn

Resolves #184 by implementing the signed integer encoders and decoders.

The `int(uint(` is not necessarily pretty, but the other options to my knowledge are:
* unsafe pointer casting (like in `nlenc`)
* manually parsing the bytes (but then endianess is a thing)

2021-02-22 13:49 UTC, mdlayher commented
Thanks for this! I will try to take a look later today.

2021-02-23 17:06 UTC, mdlayher requested changes
Overall seems fine. I would prefer not to add any new API to nlenc though: it is effectively deprecated since the addition of the attribute encoder/decoder types. Maybe I should officially add a deprecated tag on the package comment.

2021-02-23 17:06 UTC, mdlayher commented on attribute.go
> +	ae.ByteOrder.PutUint16(b,uint16(v))
I don't think this is gofmt'd.

2021-02-23 17:06 UTC, mdlayher commented on attribute_test.go
> +			name:  "uint-int32 native endian",
Just "int" for all these cases, not int32.

2021-02-23 19:33 UTC, fbegyn commented
With the `nlenc` being deprecated, I stripped out most of the code and tests in there, I only let the `put signed 32` test in there since that function is already part of the module. I've also ran `gofmt` against all the files again, looks like my last save didn't autocall it for some reason.

2021-02-23 20:11 UTC, mdlayher approved these changes
LGTM!

2021-02-23 20:12 UTC, merged